name: OpenJML Verification

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  openjml:
    name: Run OpenJML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Specify the distribution here

      - name: Download OpenJML
        run: |
          wget https://github.com/OpenJML/OpenJML/releases/download/0.21.0-alpha-0/openjml-ubuntu-22.04-0.21.0-alpha-0.zip
          unzip openjml-ubuntu-22.04-0.21.0-alpha-0.zip -d openjml
          export PATH=$PATH:$PWD/openjml/openjml-ubuntu-22.04-0.21.0-alpha-0

      - name: Verify OpenJML installation
        run: openjml/bin/openjml -version

      - name: Run OpenJML on project
        run: openjml/bin/openjml -rac -d out src/**/*.java