name: OpenJML Verification

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  openjml:
    name: Run OpenJML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Specify the distribution here

      - name: Download OpenJML
        run: |
          wget https://github.com/OpenJML/OpenJML/archive/refs/tags/0.21.0-alpha-0.tar.gz
          tar -xzf 0.21.0-alpha-0.tar.gz
          export PATH=$PATH:$PWD/OpenJML-0.21.0-alpha-0/OpenJML21/bin

      - name: Verify OpenJML installation
        run: |
          echo $PATH
          openjml -version

      - name: Run OpenJML on project
        run: openjml -rac -d out src/**/*.java