name: Verita - Cognitive Relevance

on:
  push:
    branches:
      - main    # Run on main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cognitive:
    name: Run Cognitive Relevance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository   # checkout the repository
        uses: actions/checkout@v3

      - name: Show Changed Files for Specific Commit
        run: |
          COMMIT_ID="7c52e6e"
          git fetch origin main
          git show --name-only --pretty="" $COMMIT_ID > changed_files.log
          echo "Changed files in commit $COMMIT_ID:"
          cat changed_files.log

      - name: Run OpenJML and save logs
        run: |
          shopt -s globstar
          /OpenJML-0.21.0-alpha-0/openjml -esc -progress ./**/*.java ./*.java 2>&1 | tee openjml.log
          echo "Logs have been saved to $(pwd)/openjml.log"

      - name: Send OpenJML logs to verita
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_ID=$(git rev-parse --short HEAD)
          FILE_NAME="log_${GITHUB_REPOSITORY//\//_}_${BRANCH_NAME}_${COMMIT_ID}.log"
          sudo curl --location 'https://verita-logger-api.dpacks.net' \
          --header 'x-api-key: 248frv384' \
          --form "filename=${FILE_NAME}" \
          --form "repository=${REPO_NAME}" \
          --form "branch=main" \
          --form "commit_id=${COMMIT_ID}" \
          --form "file=@$(pwd)/openjml.log"